name: IPinfo API Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 8 * * 1" # Runs at 08:00 UTC every Monday (optional)

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (required to run Newman)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Step 3: Install Newman and the HTML report generator
      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      # Step 4: Run your Postman collection with Newman
      - name: Run Newman Tests
        run: |
          newman run IPinfoCollection.json \
          --environment iIPinfoEnvironment.json \
          --global-var "api_token=${{ secrets.IPINFO_API_TOKEN }}" \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export newman-report.html

      # Step 5: Upload the detailed HTML report as an artifact
      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman-report.html
